name: deno

env:
  DENO_VERSION: 1.x
  DENOPS_PATH: "./"

runs:
  using: 'node20'

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deno-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Check Type
        run: |
          find denops -name "*.ts"| xargs deno test --unstable --no-run -A

      - name: Check with deno lint
        run: deno lint denops

      - name: Check Format
        run: |
          deno fmt --check denops

  deno-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Test
        run: |
          grep -rl Deno.test denops| xargs deno test --unstable -A
        timeout-minutes: 5
